[tool.poetry]
name = "send-email"
version = "0.1.1"
authors = [
    "Cheng Chen",
]
description = "send email to your email address"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
readme = "README.md"
packages = [{ include = "send_email" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"

[tool.poetry.scripts]
send-email = "send_email.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
