[tool.poetry]
name = "letta-agent"
version = "0.1.1"
authors = [
    "ZongHuan Wu ",
    "Cheng Chen",
]
description = "Use Mem0 to retrieve memory"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/mem0ai/mem0"
readme = "README.md"
packages = [{ include = "letta_agent" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"
letta = "*"
[tool.poetry.scripts]
letta-agent = "letta_agent.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[project]
readme = "README.md"
